# Autogenerated by devscripts/update-version.py

__version__ = '2025.10.24.135717'

RELEASE_GIT_HEAD = '9abdce1542ef43511455dd79a858559512350931'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'YAYLOLDEV/yt-dlp2'

ORIGIN = 'YAYLOLDEV/yt-dlp2'

_pkg_version = '2025.10.24.135717'
