# Autogenerated by devscripts/update-version.py

__version__ = '2025.10.24.142530'

RELEASE_GIT_HEAD = '36d15562bd67ecf39817c534b56fcd947b69fa3c'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'YAYLOLDEV/yt-dlp2'

ORIGIN = 'YAYLOLDEV/yt-dlp2'

_pkg_version = '2025.10.24.142530'
