# Autogenerated by devscripts/update-version.py

__version__ = '2025.10.24.143258'

RELEASE_GIT_HEAD = '664b1afd8eedc8a44a853cd75da0f177c9e8d875'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'YAYLOLDEV/yt-dlp2'

ORIGIN = 'YAYLOLDEV/yt-dlp2'

_pkg_version = '2025.10.24.143258'
